// Command vfs builds the WALrus loadable SQLite extension for native read
// mode (spec §9). It is loaded by the HOST's SQLite (bun:sqlite
// loadExtension, sqlite3 CLI .load) and registers per-database litestream
// read VFSes on demand via the walrus_vfs_attach() SQL function —
// multi-tenant, unlike the env-var single-replica litestream-ext sample.
//
// Build:
//
//	go build -buildmode=c-shared -tags "vfs SQLITE3VFS_LOADABLE_EXT" \
//	  -o libwalrus_vfs.dylib ./bindings/vfs
//
// The VFS name is generated by SQLite's sqlite3_vfs_register through the
// psanford/sqlite3vfs shim; pages stream as LTX from object storage.
package main

/*
#include "binding/sqlite3.h"
#include "binding/sqlite3vfs.h"
*/
import "C"

import (
	"fmt"
	"log/slog"
	"os"
	"sync"

	litestream "github.com/benbjohnson/litestream"
	_ "github.com/benbjohnson/litestream/file"
	_ "github.com/benbjohnson/litestream/s3"
	"github.com/psanford/sqlite3vfs"
)

// attached maps VFS names to their clients so a name can be reused safely.
var (
	attachMu sync.Mutex
	attached = map[string]bool{}
)

//export WalrusVFSAttach
func WalrusVFSAttach(name, replicaURL, accessKeyID, secretAccessKey *C.char) *C.char {
	n := C.GoString(name)
	url := C.GoString(replicaURL)
	key := C.GoString(accessKeyID)
	secret := C.GoString(secretAccessKey)

	attachMu.Lock()
	defer attachMu.Unlock()
	if n == "" {
		return C.CString("walrus_vfs_attach: vfs name required")
	}
	if attached[n] {
		return nil // already registered in this process
	}

	client, err := litestream.NewReplicaClientFromURL(url)
	if err != nil {
		return C.CString(fmt.Sprintf("walrus_vfs_attach: %v", err))
	}
	// litestream's s3 client reads credentials from env when the URL omits them
	if key != "" && secret != "" {
		os.Setenv("AWS_ACCESS_KEY_ID", key)
		os.Setenv("AWS_SECRET_ACCESS_KEY", secret)
	}
	// Credentials for S3 endpoints travel in the replica URL query string
	// (litestream reads them from the URL); pass through env fallbacks.
	vfs := litestream.NewVFS(client, noOpLogger())
	vfs.WriteEnabled = false // read-only: writes go through the WALrus runtime
	if err := sqlite3vfs.RegisterVFS(n, vfs); err != nil {
		return C.CString(fmt.Sprintf("walrus_vfs_attach: %v", err))
	}
	attached[n] = true
	return nil
}

func main() {}

func noOpLogger() *slog.Logger { return slog.New(slog.DiscardHandler) }
