// Command vfs builds the walrusd loadable SQLite extension for native read
// mode (spec §9). It is loaded by the HOST's SQLite (bun:sqlite
// loadExtension, sqlite3 CLI .load) and registers per-database litestream
// read VFSes on demand via the walrusd_vfs_attach() SQL function —
// multi-tenant, unlike the env-var single-replica litestream-ext sample.
//
// Build:
//
//	go build -buildmode=c-shared -tags "vfs SQLITE3VFS_LOADABLE_EXT" \
//	  -o libwalrusd_vfs.dylib ./bindings/vfs
//
// The VFS name is generated by SQLite's sqlite3_vfs_register through the
// psanford/sqlite3vfs shim; pages stream as LTX from object storage.
package main

/*
#include "binding/sqlite3.h"
#include "binding/sqlite3vfs.h"
*/
import "C"

import (
	"fmt"
	"log/slog"
	"sync"

	litestream "github.com/benbjohnson/litestream"
	_ "github.com/benbjohnson/litestream/file"
	"github.com/benbjohnson/litestream/s3"
	"github.com/psanford/sqlite3vfs"
)

// attached maps VFS names to their clients so a name can be reused safely.
var (
	attachMu sync.Mutex
	attached = map[string]bool{}
)

//export WalrusdVFSAttach
func WalrusdVFSAttach(name, replicaURL, accessKeyID, secretAccessKey *C.char) *C.char {
	n := C.GoString(name)
	url := C.GoString(replicaURL)
	key := C.GoString(accessKeyID)
	secret := C.GoString(secretAccessKey)

	attachMu.Lock()
	defer attachMu.Unlock()
	if n == "" {
		return C.CString("walrusd_vfs_attach: vfs name required")
	}
	if attached[n] {
		return nil // already registered in this process
	}

	client, err := litestream.NewReplicaClientFromURL(url)
	if err != nil {
		return C.CString(fmt.Sprintf("walrusd_vfs_attach: %v", err))
	}
	// Configure credentials on this client only; process-global environment
	// variables would leak one tenant's credentials to every other tenant.
	if key != "" && secret != "" {
		s3Client, ok := client.(*s3.ReplicaClient)
		if !ok {
			return C.CString("walrusd_vfs_attach: credentials require an s3 replica URL")
		}
		s3Client.AccessKeyID = key
		s3Client.SecretAccessKey = secret
	}
	vfs := litestream.NewVFS(client, noOpLogger())
	vfs.WriteEnabled = false // read-only: writes go through the walrusd runtime
	if err := sqlite3vfs.RegisterVFS(n, vfs); err != nil {
		return C.CString(fmt.Sprintf("walrusd_vfs_attach: %v", err))
	}
	attached[n] = true
	return nil
}

func main() {}

func noOpLogger() *slog.Logger { return slog.New(slog.DiscardHandler) }
